#!/usr/bin/env python3
"""
DAG summarisation engine for lossless-code.

Collects unsummarised messages, chunks them, calls the summary model,
writes summary nodes to the DAG, and cascades to higher depths when
the node count at any depth exceeds the configured threshold.
"""

import argparse
import logging
import os
import sys
import json
import time

# Ensure scripts/ is importable
sys.path.insert(0, os.path.dirname(os.path.abspath(__file__)))

import db

# ---------------------------------------------------------------------------
# Logging
# ---------------------------------------------------------------------------

_log = logging.getLogger("lossless-code")
if not _log.handlers:
    _log.addHandler(logging.StreamHandler(sys.stderr))
    _log.setLevel(logging.WARNING)

# ---------------------------------------------------------------------------
# Provider state (in-memory, per-process)
# ---------------------------------------------------------------------------

_provider_state = {
    "provider": None,
    "model": None,
    "auto_detected": False,
    "last_error": None,
    "last_error_time": None,
    "consecutive_failures": 0,
}


def get_provider_info() -> dict:
    """Return current provider state for status display."""
    return dict(_provider_state)


# ---------------------------------------------------------------------------
# Provider auto-detection
# ---------------------------------------------------------------------------

def _detect_provider(cfg: dict) -> tuple:
    """
    Auto-detect the best available LLM provider from environment.

    Returns (provider, model) or (None, None) when nothing is available.
    Priority: Anthropic API key > OpenAI API key > openaiBaseUrl (Ollama) > None.
    """
    # 1. Anthropic API key or OAuth credentials
    if os.environ.get("ANTHROPIC_API_KEY"):
        return ("anthropic", cfg.get("summaryModel") or "claude-haiku-4-5-20251001")

    # Check credentials file for OAuth token
    creds_path = os.path.join(os.path.expanduser("~"), ".claude", ".credentials.json")
    try:
        with open(creds_path) as f:
            creds = json.load(f)
        if creds.get("claudeAiOauth", {}).get("accessToken"):
            return ("anthropic", cfg.get("summaryModel") or "claude-haiku-4-5-20251001")
    except (FileNotFoundError, json.JSONDecodeError, KeyError):
        pass

    if os.environ.get("CLAUDE_CODE_OAUTH_TOKEN"):
        return ("anthropic", cfg.get("summaryModel") or "claude-haiku-4-5-20251001")

    # 2. OpenAI API key
    if os.environ.get("OPENAI_API_KEY"):
        return ("openai", cfg.get("summaryModel") or "gpt-4.1-mini")

    # 3. openaiBaseUrl set (likely Ollama or local)
    base_url = cfg.get("openaiBaseUrl") or os.environ.get("OPENAI_BASE_URL")
    if base_url:
        return ("openai", cfg.get("summaryModel") or "llama3")

    # 4. Nothing available
    return (None, None)


def _get_anthropic_auth() -> dict:
    """
    Resolve Anthropic authentication from multiple sources (in priority order):

    1. ANTHROPIC_API_KEY environment variable (standard API key auth)
    2. Claude Code OAuth token from ~/.claude/.credentials.json
       (setup-token generated by `claude setup-token`) — requires
       ANTHROPIC_BASE_URL pointing to a compatible proxy, since
       api.anthropic.com does not accept OAuth tokens directly.
    3. CLAUDE_CODE_OAUTH_TOKEN environment variable (same caveat)

    Returns a dict to unpack into anthropic.Anthropic(**auth):
      - {"api_key": "sk-ant-api..."} for API key auth
      - {"auth_token": "sk-ant-oat..."} for OAuth/setup-token auth
        (only useful with a proxy that supports OAuth, e.g. OpenClaw)
      - {} if nothing found (lets SDK try its own resolution)
    """
    # 1. Standard API key (works with api.anthropic.com)
    key = os.environ.get("ANTHROPIC_API_KEY")
    if key:
        return {"api_key": key}

    # 2. Claude Code credentials file (setup-token / OAuth)
    #    NOTE: OAuth tokens only work with proxies that support them.
    #    Set ANTHROPIC_BASE_URL to your proxy if using setup-tokens.
    creds_path = os.path.join(os.path.expanduser("~"), ".claude", ".credentials.json")
    try:
        with open(creds_path) as f:
            creds = json.load(f)
        oauth = creds.get("claudeAiOauth", {})
        access_token = oauth.get("accessToken")
        if access_token:
            return {"auth_token": access_token}
    except (FileNotFoundError, json.JSONDecodeError, KeyError):
        pass

    # 3. OAuth token env var (set by Claude Code runtime)
    oauth_env = os.environ.get("CLAUDE_CODE_OAUTH_TOKEN")
    if oauth_env:
        return {"auth_token": oauth_env}

    return {}


# ---------------------------------------------------------------------------
# Model capability map (R8)
# ---------------------------------------------------------------------------

MODEL_CONTEXT_WINDOWS = {
    "claude-haiku": 200_000,
    "claude-sonnet": 200_000,
    "claude-opus": 200_000,
    "gpt-4o-mini": 128_000,
    "gpt-4o": 128_000,
    "gpt-4.1-mini": 1_000_000,
    "gpt-4.1-nano": 1_000_000,
    "gpt-4.1": 1_000_000,
    "llama3": 8_192,
    "mistral": 32_000,
    "MiniMax": 1_000_000,
}


def _get_context_window(model: str) -> int:
    """Return context window size for a model. Defaults to 8192 for unknown models."""
    if not model:
        return 8192
    for prefix, size in MODEL_CONTEXT_WINDOWS.items():
        if model.startswith(prefix):
            return size
    return 8192


def estimate_tokens(text: str) -> int:
    """Rough token estimate: ~4 chars per token."""
    return max(1, len(text) // 4)


def _log_provider_error(category: str, provider: str, model: str, error: Exception) -> None:
    """Log a provider error to stderr and provider.log."""
    _provider_state["last_error"] = category
    _provider_state["last_error_time"] = time.time()
    _provider_state["consecutive_failures"] += 1
    # Sanitize error message to avoid leaking API keys/tokens
    safe_msg = type(error).__name__
    if hasattr(error, "status_code"):
        safe_msg += f" (HTTP {error.status_code})"
    _log.warning("[lossless-code] %s (%s:%s): %s", category, provider, model, safe_msg)
    # Append to provider.log for hook visibility
    try:
        log_path = db.LOSSLESS_HOME / "provider.log"
        # Rotate at ~100KB
        if log_path.exists() and log_path.stat().st_size > 100_000:
            log_path.write_text("")
        with open(log_path, "a") as f:
            f.write(f"{time.strftime('%Y-%m-%d %H:%M:%S')} [{category}] {provider}:{model} {safe_msg}\n")
    except OSError:
        pass


def call_llm(prompt: str, cfg: dict, json_mode: bool = False) -> str:
    """
    Call an LLM with an arbitrary prompt. Supports Anthropic, OpenAI, and any
    OpenAI-compatible provider (Ollama, Groq, Together AI, etc.) via openaiBaseUrl.

    Auto-detects the provider when summaryProvider is None.
    Returns the model response text, or empty string if the API is unavailable.
    """
    provider = cfg.get("summaryProvider")
    model = cfg.get("summaryModel", "claude-haiku-4-5-20251001")

    # Auto-detect provider when not explicitly set
    if not provider:
        provider, detected_model = _detect_provider(cfg)
        if not model or model == "claude-haiku-4-5-20251001":
            model = detected_model or model
        _provider_state["auto_detected"] = True
    else:
        _provider_state["auto_detected"] = False

    _provider_state["provider"] = provider
    _provider_state["model"] = model

    if not provider:
        return ""

    if provider == "openai":
        try:
            from openai import OpenAI

            base_url = cfg.get("openaiBaseUrl") or os.environ.get("OPENAI_BASE_URL")
            api_key = os.environ.get("OPENAI_API_KEY") or ("not-needed" if base_url else None)
            if not api_key:
                return ""
            client = OpenAI(base_url=base_url, api_key=api_key)
            kwargs = {
                "model": model,
                "max_tokens": 2048,
                "messages": [{"role": "user", "content": prompt}],
            }
            if json_mode:
                kwargs["response_format"] = {"type": "json_object"}
            response = client.chat.completions.create(**kwargs)
            _provider_state["consecutive_failures"] = 0
            _provider_state["last_error"] = None
            return response.choices[0].message.content
        except Exception as e:
            cat = "llm_error"
            try:
                import openai as _oai
                if isinstance(e, _oai.AuthenticationError):
                    cat = "auth_error"
                elif isinstance(e, _oai.RateLimitError):
                    cat = "rate_limit"
                elif isinstance(e, _oai.APIConnectionError):
                    cat = "connection_error"
            except ImportError:
                pass
            _log_provider_error(cat, provider, model, e)

    elif provider == "anthropic":
        try:
            import anthropic

            auth = _get_anthropic_auth()
            base_url = cfg.get("anthropicBaseUrl") or os.environ.get("ANTHROPIC_BASE_URL")
            if base_url:
                auth["base_url"] = base_url
            client = anthropic.Anthropic(**auth)
            response = client.messages.create(
                model=model,
                max_tokens=2048,
                messages=[{"role": "user", "content": prompt}],
            )
            # Handle reasoning models that return ThinkingBlock + TextBlock
            for block in response.content:
                if hasattr(block, "text"):
                    _provider_state["consecutive_failures"] = 0
                    _provider_state["last_error"] = None
                    return block.text
            return ""
        except Exception as e:
            cat = "llm_error"
            try:
                import anthropic as _anth
                if isinstance(e, _anth.AuthenticationError):
                    cat = "auth_error"
                elif isinstance(e, _anth.RateLimitError):
                    cat = "rate_limit"
                elif isinstance(e, _anth.APIConnectionError):
                    cat = "connection_error"
            except ImportError:
                pass
            _log_provider_error(cat, provider, model, e)

    elif provider == "local":
        # Route to extractive fallback (handled by caller)
        return ""

    return ""


def _extractive_summary(text: str) -> str:
    """TF-IDF sentence scoring for extractive summarisation (stdlib only)."""
    import math
    import re
    from collections import Counter

    # Split into sentences (simple heuristic)
    sentences = re.split(r'(?<=[.!?])\s+|\n\n+|\n(?=\[)', text.strip())
    sentences = [s.strip() for s in sentences if s.strip() and len(s.strip()) > 10]

    if len(sentences) <= 5:
        return "\n".join(sentences)

    # Tokenize: lowercase alphanumeric words
    def tokenize(s):
        return re.findall(r'[a-z0-9_./]+', s.lower())

    # Compute term frequency per sentence
    sentence_tfs = []
    for s in sentences:
        tokens = tokenize(s)
        sentence_tfs.append(Counter(tokens))

    # Compute document frequency (how many sentences contain each term)
    df = Counter()
    for tf in sentence_tfs:
        for term in tf:
            df[term] += 1

    n = len(sentences)
    # Score each sentence by sum of TF-IDF weights
    scores = []
    for i, tf in enumerate(sentence_tfs):
        score = 0.0
        for term, count in tf.items():
            idf = math.log((n + 1) / (df[term] + 1)) + 1
            score += count * idf
        # Boost sentences with decision/action keywords
        s_lower = sentences[i].lower()
        if any(kw in s_lower for kw in ("decided", "decision", "created", "fixed", "error", "changed")):
            score *= 1.3
        scores.append((score, i))

    # Select top-K sentences, preserving original order
    k = min(max(5, len(sentences) // 3), 15)
    top_indices = sorted([idx for _, idx in sorted(scores, reverse=True)[:k]])
    return "\n".join(sentences[i] for i in top_indices)


def call_summary_model(text: str, cfg: dict) -> str:
    """
    Call an LLM to produce a summary of conversation turns.

    Composes a summarisation prompt and delegates to call_llm().
    Falls back to a simple extractive summary if the API is unavailable.
    """
    prompt = (
        "Summarise the following conversation turns concisely, preserving all "
        "key decisions, facts, file paths, commands, and outputs. Do not omit "
        "anything actionable. Output ONLY the summary, no preamble.\n\n"
        f"{text}"
    )

    result = call_llm(prompt, cfg)
    if result:
        return result

    # Degraded mode warning (R6)
    provider = _provider_state.get("provider") or "none"
    model = _provider_state.get("model") or "none"
    _log.warning(
        "[lossless-code] LLM unavailable (%s:%s), using extractive fallback. "
        "Run 'lcc status' for details.", provider, model
    )

    # Fallback: TF-IDF sentence scoring (stdlib only, R9)
    return _extractive_summary(text)


def format_messages_for_summary(messages: list[dict], model: str = None) -> str:
    """Format a chunk of messages into a text block for summarisation."""
    ctx_window = _get_context_window(model) if model else 8192
    # Only truncate individual messages for small-context models
    max_msg_chars = 4000 if ctx_window < 32_000 else 20_000
    parts = []
    for m in messages:
        role = m["role"]
        content = m["content"]
        if len(content) > max_msg_chars:
            content = content[:max_msg_chars - 200] + "\n... [truncated]"
        prefix = f"[{role}]"
        if m.get("tool_name"):
            prefix = f"[{role}:{m['tool_name']}]"
        parts.append(f"{prefix} {content}")
    return "\n\n".join(parts)


def summarise_messages(session_id: str = None) -> int:
    """
    Run depth-0 summarisation on unsummarised messages.
    Returns the number of summary nodes created.
    """
    cfg = db.load_config()
    chunk_size = cfg.get("chunkSize", 20)

    messages = db.get_unsummarised(session_id)
    if not messages:
        return 0

    created = 0
    # Chunk messages
    for i in range(0, len(messages), chunk_size):
        chunk = messages[i : i + chunk_size]
        text = format_messages_for_summary(chunk)
        summary_text = call_summary_model(text, cfg)

        summary_id = db.gen_summary_id()
        source_ids = [("message", str(m["id"])) for m in chunk]
        token_count = estimate_tokens(summary_text)

        # Determine session_id — use chunk's if all same session
        chunk_sessions = set(m["session_id"] for m in chunk)
        sid = chunk_sessions.pop() if len(chunk_sessions) == 1 else None

        db.store_summary(
            summary_id=summary_id,
            content=summary_text,
            depth=0,
            source_ids=source_ids,
            session_id=sid,
            token_count=token_count,
        )
        db.mark_summarised([m["id"] for m in chunk])
        created += 1

    return created


def cascade_summaries(session_id: str = None) -> int:
    """
    If summaries at any depth exceed the threshold, summarise them into
    the next depth level. Cascades until under threshold or max depth.
    """
    cfg = db.load_config()
    threshold = cfg.get("depthThreshold", 10)
    max_depth = cfg.get("incrementalMaxDepth", -1)

    total_created = 0
    depth = 0

    while True:
        if max_depth >= 0 and depth >= max_depth:
            break

        summaries = db.get_summaries_at_depth(depth, session_id)
        if len(summaries) <= threshold:
            break

        chunk_size = cfg.get("chunkSize", 20)
        created = 0

        for i in range(0, len(summaries), chunk_size):
            chunk = summaries[i : i + chunk_size]
            text = "\n\n---\n\n".join(s["content"] for s in chunk)
            summary_text = call_summary_model(text, cfg)

            summary_id = db.gen_summary_id()
            source_ids = [("summary", s["id"]) for s in chunk]
            token_count = estimate_tokens(summary_text)

            chunk_sessions = set(s["session_id"] for s in chunk if s["session_id"])
            sid = chunk_sessions.pop() if len(chunk_sessions) == 1 else None

            db.store_summary(
                summary_id=summary_id,
                content=summary_text,
                depth=depth + 1,
                source_ids=source_ids,
                session_id=sid,
                token_count=token_count,
            )
            created += 1

        total_created += created
        depth += 1

    return total_created


def run_full_summarisation(session_id: str = None) -> dict:
    """Run both message summarisation and depth cascading."""
    depth0 = summarise_messages(session_id)
    cascaded = cascade_summaries(session_id)
    return {"depth_0_created": depth0, "cascaded_created": cascaded}


def main():
    parser = argparse.ArgumentParser(description="Run DAG summarisation")
    parser.add_argument("--session", help="Session ID to summarise (default: all)")
    args = parser.parse_args()

    result = run_full_summarisation(args.session)
    print(json.dumps(result))


if __name__ == "__main__":
    main()
